#!/bin/bash



# Test to see if the binary has been extracted -- if not, extract it
cd /tmp/iou-instances/l2_switch
iou_bin=./i86bi-linux-l2-adventerprisek9-15.6.0.9S.bin
iou_bin_zip=./i86bi-linux-l2-adventerprisek9-15.6.0.9S.bin.zip

# Test to see if the IOU code is already running.  If so, do nothing

ps_output=$(ps aux | grep $iou_bin | grep -v grep)

if [[ $ps_output != *"i86bi-linux-l2"* ]]
then
   echo "$iou_bin is not running.  Starting......."
   if [[ ! -f $iou_bin ]]
   then 
      echo ""
      echo "Extracting the executable ....."
      unzip $iou_bin_zip
   else
      echo ""
      echo $iou_bin, " already exists.  Starting up"   
   fi
   #Run the switch
   if [[ ! -f $iou_bin ]] 
   then
      echo "the binary did not extract for some reason"
   else 
      ./wrapper.bin -m ./i86bi-linux-l2-adventerprisek9-15.6.0.9S.bin -p 5001 -- 501
   fi
else
   echo "$iou_bin is already running.  Continuing ....."
fi


